# æ™ºèƒ½å……é›»é›»æ± ç®¡ç†ç³»çµ± - Home Assistant è¼”åŠ©å¯¦é«”é…ç½®
# å°‡æ­¤å…§å®¹æ·»åŠ åˆ°æ‚¨çš„ configuration.yaml æˆ–å–®ç¨çš„ helpers.yaml æ–‡ä»¶ä¸­

# è¼¸å…¥æ—¥æœŸæ™‚é–“ - è¨˜éŒ„ä¸Šæ¬¡å……é›»æ™‚é–“
input_datetime:
  # ç‰§ç”°é›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“
  makita_last_charge:
    name: "ç‰§ç”°é›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“"
    has_date: true
    has_time: true
    icon: mdi:battery-charging
    
  # ENELOOP 3è™Ÿé›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“
  eneloop_aa_last_charge:
    name: "ENELOOP 3è™Ÿé›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“"
    has_date: true
    has_time: true
    icon: mdi:battery-charging
    
  # ENELOOP 4è™Ÿé›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“
  eneloop_aaa_last_charge:
    name: "ENELOOP 4è™Ÿé›»æ± ä¸Šæ¬¡å……é›»æ™‚é–“"
    has_date: true
    has_time: true
    icon: mdi:battery-charging

# è¼¸å…¥å¸ƒæž—å€¼ - ç³»çµ±é–‹é—œæŽ§åˆ¶
input_boolean:
  # é›»æ± ç®¡ç†ç³»çµ±ç¸½é–‹é—œ
  battery_management_enabled:
    name: "é›»æ± ç®¡ç†ç³»çµ±"
    icon: mdi:battery-sync
    
  # è‡ªå‹•ç¶­è­·å……é›»é–‹é—œ
  battery_auto_maintenance:
    name: "è‡ªå‹•ç¶­è­·å……é›»"
    icon: mdi:battery-sync-outline
    
  # å……é›»é€šçŸ¥é–‹é—œ
  battery_charging_notifications:
    name: "å……é›»é€šçŸ¥"
    icon: mdi:bell-ring
    
  # ç‰§ç”°é›»æ± å€‹åˆ¥æŽ§åˆ¶
  makita_charging_enabled:
    name: "ç‰§ç”°é›»æ± å……é›»ç®¡ç†"
    icon: mdi:battery
    
  # ENELOOP 3è™Ÿé›»æ± å€‹åˆ¥æŽ§åˆ¶
  eneloop_aa_charging_enabled:
    name: "ENELOOP 3è™Ÿé›»æ± å……é›»ç®¡ç†"
    icon: mdi:battery
    
  # ENELOOP 4è™Ÿé›»æ± å€‹åˆ¥æŽ§åˆ¶
  eneloop_aaa_charging_enabled:
    name: "ENELOOP 4è™Ÿé›»æ± å……é›»ç®¡ç†"
    icon: mdi:battery

# è¼¸å…¥æ•¸å­— - å……é›»æ™‚é–“è¨­å®š
input_number:
  # ç‰§ç”°é›»æ± å……é›»æ™‚é–“ (åˆ†é˜)
  makita_charging_time:
    name: "ç‰§ç”°é›»æ± å……é›»æ™‚é–“"
    min: 30
    max: 180
    step: 15
    initial: 90
    unit_of_measurement: "åˆ†é˜"
    icon: mdi:timer
    
  # ENELOOP 3è™Ÿé›»æ± å……é›»æ™‚é–“ (åˆ†é˜)
  eneloop_aa_charging_time:
    name: "ENELOOP 3è™Ÿé›»æ± å……é›»æ™‚é–“"
    min: 60
    max: 360
    step: 15
    initial: 240
    unit_of_measurement: "åˆ†é˜"
    icon: mdi:timer
    
  # ENELOOP 4è™Ÿé›»æ± å……é›»æ™‚é–“ (åˆ†é˜)
  eneloop_aaa_charging_time:
    name: "ENELOOP 4è™Ÿé›»æ± å……é›»æ™‚é–“"
    min: 60
    max: 300
    step: 15
    initial: 210
    unit_of_measurement: "åˆ†é˜"
    icon: mdi:timer
    
  # ç¶­è­·å……é›»é€±æœŸ (å¤©)
  makita_maintenance_cycle:
    name: "ç‰§ç”°é›»æ± ç¶­è­·é€±æœŸ"
    min: 7
    max: 90
    step: 1
    initial: 30
    unit_of_measurement: "å¤©"
    icon: mdi:calendar-sync
    
  eneloop_maintenance_cycle:
    name: "ENELOOPé›»æ± ç¶­è­·é€±æœŸ"
    min: 14
    max: 120
    step: 1
    initial: 60
    unit_of_measurement: "å¤©"
    icon: mdi:calendar-sync

# è¼¸å…¥é¸æ“‡ - å……é›»æ¨¡å¼
input_select:
  # å……é›»æ¨¡å¼é¸æ“‡
  battery_charging_mode:
    name: "å……é›»æ¨¡å¼"
    options:
      - "æ‰‹å‹•æ¨¡å¼"
      - "è‡ªå‹•æ¨¡å¼"
      - "ç¶­è­·æ¨¡å¼"
      - "åœç”¨"
    initial: "è‡ªå‹•æ¨¡å¼"
    icon: mdi:battery-sync

# è¼¸å…¥æ–‡å­— - ç³»çµ±ç‹€æ…‹é¡¯ç¤º
input_text:
  # ç³»çµ±ç‹€æ…‹
  battery_system_status:
    name: "é›»æ± ç³»çµ±ç‹€æ…‹"
    max: 255
    initial: "ç³»çµ±å°±ç·’"
    icon: mdi:information
    
  # æœ€å¾Œæ“ä½œè¨˜éŒ„
  battery_last_operation:
    name: "æœ€å¾Œæ“ä½œ"
    max: 255
    initial: "ç„¡"
    icon: mdi:history

# æ„Ÿæ¸¬å™¨ - è¨ˆç®—è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸
sensor:
  - platform: template
    sensors:
      # ç‰§ç”°é›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸
      makita_days_since_charge:
        friendly_name: "ç‰§ç”°é›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸"
        unit_of_measurement: "å¤©"
        icon_template: mdi:calendar-clock
        value_template: >
          {% set last_charge = states('input_datetime.makita_last_charge') %}
          {% if last_charge != 'unknown' and last_charge != 'unavailable' %}
            {% set last_charge_date = strptime(last_charge, '%Y-%m-%d %H:%M:%S') %}
            {% set now = now() %}
            {{ (now - last_charge_date).days }}
          {% else %}
            999
          {% endif %}
      
      # ENELOOP 3è™Ÿé›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸
      eneloop_aa_days_since_charge:
        friendly_name: "ENELOOP 3è™Ÿé›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸"
        unit_of_measurement: "å¤©"
        icon_template: mdi:calendar-clock
        value_template: >
          {% set last_charge = states('input_datetime.eneloop_aa_last_charge') %}
          {% if last_charge != 'unknown' and last_charge != 'unavailable' %}
            {% set last_charge_date = strptime(last_charge, '%Y-%m-%d %H:%M:%S') %}
            {% set now = now() %}
            {{ (now - last_charge_date).days }}
          {% else %}
            999
          {% endif %}
      
      # ENELOOP 4è™Ÿé›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸
      eneloop_aaa_days_since_charge:
        friendly_name: "ENELOOP 4è™Ÿé›»æ± è·é›¢ä¸Šæ¬¡å……é›»å¤©æ•¸"
        unit_of_measurement: "å¤©"
        icon_template: mdi:calendar-clock
        value_template: >
          {% set last_charge = states('input_datetime.eneloop_aaa_last_charge') %}
          {% if last_charge != 'unknown' and last_charge != 'unavailable' %}
            {% set last_charge_date = strptime(last_charge, '%Y-%m-%d %H:%M:%S') %}
            {% set now = now() %}
            {{ (now - last_charge_date).days }}
          {% else %}
            999
          {% endif %}

# è‡ªå‹•åŒ–ç¯„ä¾‹ (å¯é¸)
automation:
  # æ¯æ—¥æª¢æŸ¥ç¶­è­·å……é›»éœ€æ±‚
  - alias: "é›»æ± ç¶­è­·æª¢æŸ¥"
    description: "æ¯æ—¥æ—©ä¸Š8é»žæª¢æŸ¥æ˜¯å¦éœ€è¦ç¶­è­·å……é›»"
    trigger:
      - platform: time
        at: "08:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.battery_management_enabled
        state: 'on'
      - condition: state
        entity_id: input_boolean.battery_auto_maintenance
        state: 'on'
    action:
      - service: notify.notify
        data:
          title: "ðŸ”‹ é›»æ± ç¶­è­·æª¢æŸ¥"
          message: >
            ç³»çµ±æ­£åœ¨æª¢æŸ¥é›»æ± ç¶­è­·éœ€æ±‚...
            ç‰§ç”°é›»æ± ï¼š{{ states('sensor.makita_days_since_charge') }}å¤©
            ENELOOP 3è™Ÿï¼š{{ states('sensor.eneloop_aa_days_since_charge') }}å¤©
            ENELOOP 4è™Ÿï¼š{{ states('sensor.eneloop_aaa_days_since_charge') }}å¤©
